from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, View
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from .models import Post, Comment, Tag
from .forms import PostForm, CommentForm, UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.contrib import messages
from django.contrib.auth import login
from django.db.models import Q

# Post List and search
class PostListView(ListView):
    model = Post
        template_name = 'blog/post_list.html'
            context_object_name = 'posts'
                paginate_by = 10

                    def get_queryset(self):
                            qs = super().get_queryset()
                                    q = self.request.GET.get('q', '')
                                            tag = self.kwargs.get('tag', None)
                                                    if q:
                                                                qs = qs.filter(Q(title__icontains=q) | Q(content__icontains=q) | Q(tags__name__icontains=q)).distinct()
                                                                        if tag:
                                                                                    qs = qs.filter(tags__name=tag)
                                                                                            return qs

                                                                                            class PostDetailView(DetailView):
                                                                                                model = Post
                                                                                                    template_name = 'blog/post_detail.html'

                                                                                                        def get_context_data(self, **kwargs):
                                                                                                                ctx = super().get_context_data(**kwargs)
                                                                                                                        ctx['comment_form'] = CommentForm()
                                                                                                                                return ctx

                                                                                                                                class PostCreateView(LoginRequiredMixin, CreateView):
                                                                                                                                    model = Post
                                                                                                                                        form_class = PostForm
                                                                                                                                            template_name = 'blog/post_form.html'

                                                                                                                                                def form_valid(self, form):
                                                                                                                                                        form.instance.author = self.request.user
                                                                                                                                                                # PostForm.save handles tags if called with commit=True
                                                                                                                                                                        return super().form_valid(form)

                                                                                                                                                                        class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
                                                                                                                                                                            model = Post
                                                                                                                                                                                form_class = PostForm
                                                                                                                                                                                    template_name = 'blog/post_form.html'

                                                                                                                                                                                        def get_initial(self):
                                                                                                                                                                                                initial = super().get_initial()
                                                                                                                                                                                                        # prefill tags_field from existing tags
                                                                                                                                                                                                                initial['tags_field'] = ', '.join([t.name for t in self.object.tags.all()])
                                                                                                                                                                                                                        return initial

                                                                                                                                                                                                                            def form_valid(self, form):
                                                                                                                                                                                                                                    # clear previous tags then save new ones
                                                                                                                                                                                                                                            self.object.tags.clear()
                                                                                                                                                                                                                                                    return super().form_valid(form)

                                                                                                                                                                                                                                                        def test_func(self):
                                                                                                                                                                                                                                                                post = self.get_object()
                                                                                                                                                                                                                                                                        return self.request.user == post.author

                                                                                                                                                                                                                                                                        class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
                                                                                                                                                                                                                                                                            model = Post
                                                                                                                                                                                                                                                                                success_url = reverse_lazy('blog:post_list')
                                                                                                                                                                                                                                                                                    template_name = 'blog/post_confirm_delete.html'

                                                                                                                                                                                                                                                                                        def test_func(self):
                                                                                                                                                                                                                                                                                                post = self.get_object()
                                                                                                                                                                                                                                                                                                        return self.request.user == post.author

                                                                                                                                                                                                                                                                                                        # Comments
                                                                                                                                                                                                                                                                                                        def add_comment(request, pk):
                                                                                                                                                                                                                                                                                                            post = get_object_or_404(Post, pk=pk)
                                                                                                                                                                                                                                                                                                                if not request.user.is_authenticated:
                                                                                                                                                                                                                                                                                                                        messages.error(request, "You must be logged in to comment.")
                                                                                                                                                                                                                                                                                                                                return redirect('login')
                                                                                                                                                                                                                                                                                                                                    if request.method == 'POST':
                                                                                                                                                                                                                                                                                                                                            form = CommentForm(request.POST)
                                                                                                                                                                                                                                                                                                                                                    if form.is_valid():
                                                                                                                                                                                                                                                                                                                                                                c = form.save(commit=False)
                                                                                                                                                                                                                                                                                                                                                                            c.author = request.user
                                                                                                                                                                                                                                                                                                                                                                                        c.post = post
                                                                                                                                                                                                                                                                                                                                                                                                    c.save()
                                                                                                                                                                                                                                                                                                                                                                                                                messages.success(request, "Comment added.")
                                                                                                                                                                                                                                                                                                                                                                                                                    return redirect(post.get_absolute_url())

                                                                                                                                                                                                                                                                                                                                                                                                                    class CommentUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
                                                                                                                                                                                                                                                                                                                                                                                                                        model = Comment
                                                                                                                                                                                                                                                                                                                                                                                                                            fields = ['content']
                                                                                                                                                                                                                                                                                                                                                                                                                                template_name = 'blog/comment_form.html'

                                                                                                                                                                                                                                                                                                                                                                                                                                    def test_func(self):
                                                                                                                                                                                                                                                                                                                                                                                                                                            comment = self.get_object()
                                                                                                                                                                                                                                                                                                                                                                                                                                                    return self.request.user == comment.author

                                                                                                                                                                                                                                                                                                                                                                                                                                                    class CommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
                                                                                                                                                                                                                                                                                                                                                                                                                                                        model = Comment
                                                                                                                                                                                                                                                                                                                                                                                                                                                            template_name = 'blog/comment_confirm_delete.html'

                                                                                                                                                                                                                                                                                                                                                                                                                                                                def get_success_url(self):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return self.object.post.get_absolute_url()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def test_func(self):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    comment = self.get_object()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return self.request.user == comment.author

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Auth: registration & profile
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def register(request):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if request.method == 'POST':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        form = UserRegisterForm(request.POST)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if form.is_valid():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            user = form.save()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # create profile implicitly by signal or create here
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # from .models import Profile
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Profile.objects.create(user=user)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            login(request, user)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        messages.success(request, "Registration successful.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return redirect('blog:post_list')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                form = UserRegisterForm()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return render(request, 'registration/register.html', {'form': form})

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    from django.contrib.auth.decorators import login_required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    @login_required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def profile(request):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if request.method == 'POST':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                uform = UserUpdateForm(request.POST, instance=request.user)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        pform = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if uform.is_valid() and pform.is_valid():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            uform.save()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        pform.save()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    messages.success(request, 'Profile updated.')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return redirect('blog:profile')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            uform = UserUpdateForm(instance=request.user)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                pform = ProfileUpdateForm(instance=request.user.profile)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        except Exception:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # in case no profile exists
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                from .models import Profile
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Profile.objects.get_or_create(user=request.user)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        pform = ProfileUpdateForm(instance=request.user.profile)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return render(request, 'registration/profile.html', {'uform': uform, 'pform': pform})
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            